In [32]:
from pycaret.datasets import get_data
anomaly = get_data('anomaly')

       Col1      Col2      Col3  ...      Col8      Col9     Col10
0  0.263995  0.764929  0.138424  ...  0.608234  0.723782  0.733591
1  0.546092  0.653975  0.065575  ...  0.331679  0.429297  0.367422
2  0.336714  0.538842  0.192801  ...  0.861309  0.899017  0.088600
3  0.092108  0.995017  0.014465  ...  0.158963  0.073715  0.208463
4  0.325261  0.805968  0.957033  ...  0.558449  0.885169  0.182754

[5 rows x 10 columns]

In [33]:
from pycaret.anomaly import *

exp_ano = setup(anomaly)

Setup Succesfully Completed!

In [34]:
anomaly

         Col1      Col2      Col3  ...      Col8      Col9     Col10
0    0.263995  0.764929  0.138424  ...  0.608234  0.723782  0.733591
1    0.546092  0.653975  0.065575  ...  0.331679  0.429297  0.367422
2    0.336714  0.538842  0.192801  ...  0.861309  0.899017  0.088600
3    0.092108  0.995017  0.014465  ...  0.158963  0.073715  0.208463
4    0.325261  0.805968  0.957033  ...  0.558449  0.885169  0.182754
..        ...       ...       ...  ...       ...       ...       ...
995  0.305055  0.656837  0.331665  ...  0.584786  0.808640  0.242762
996  0.812627  0.864258  0.616604  ...  0.472306  0.348347  0.671129
997  0.250967  0.138627  0.919703  ...  0.530324  0.779433  0.234952
998  0.502436  0.936820  0.580062  ...  0.242755  0.279385  0.538755
999  0.457991  0.017755  0.714113  ...  0.692299  0.816777  0.307592

[1000 rows x 10 columns]

In [37]:
iforest = create_model('iforest')
#plot_model(iforest)

In [38]:
knn = create_model('knn')
#plot_model(knn)

In [40]:
knn_pre = predict_model(knn,data=anomaly)

In [41]:
knn_pre

         Col1      Col2      Col3  ...     Col10  Label     Score
0    0.263995  0.764929  0.138424  ...  0.733591      0  0.558927
1    0.546092  0.653975  0.065575  ...  0.367422      0  0.477482
2    0.336714  0.538842  0.192801  ...  0.088600      0  0.676207
3    0.092108  0.995017  0.014465  ...  0.208463      1  0.804769
4    0.325261  0.805968  0.957033  ...  0.182754      0  0.630836
..        ...       ...       ...  ...       ...    ...       ...
995  0.305055  0.656837  0.331665  ...  0.242762      0  0.266822
996  0.812627  0.864258  0.616604  ...  0.671129      0  0.403480
997  0.250967  0.138627  0.919703  ...  0.234952      0  0.337727
998  0.502436  0.936820  0.580062  ...  0.538755      0  0.300265
999  0.457991  0.017755  0.714113  ...  0.307592      0  0.367867

[1000 rows x 12 columns]